import * as FileSystem from 'expo-file-system';import * as ImageManipulator from 'expo-image-manipulator';import * as ort from 'onnxruntime-react-native';import {toByteArray,fromByteArray} from 'base64-js';import jpeg from 'jpeg-js';import {encode} from 'fast-png';import type {DraftAnalysis,Slot} from '../types';import {processedPath} from './storage';
const MODELS=`${FileSystem.documentDirectory}models/`;const SEG=`${MODELS}background.onnx`;const TAG=`${MODELS}fashion-tags.onnx`;const SIZE=256;
const labels={category:['top','bottom','shoes','accessory'],color:['negro','blanco','gris','azul','rojo','verde','beige','marrón','amarillo','morado'],material:['algodón','denim','lana','cuero','nylon','poliéster','punto'],style:['minimalista','streetwear','formal','deportivo','vintage','técnico'],season:['todo el año','primavera','verano','otoño','invierno']};
let segmenter:ort.InferenceSession|null=null,classifier:ort.InferenceSession|null=null;
const softPick=(data:ArrayLike<number>,names:string[])=>{let ix=0;for(let i=1;i<Math.min(data.length,names.length);i++)if(data[i]>data[ix])ix=i;return names[ix]||''};
async function tensorFromImage(uri:string){const resized=await ImageManipulator.manipulateAsync(uri,[{resize:{width:SIZE,height:SIZE}}],{compress:1,format:ImageManipulator.SaveFormat.JPEG,base64:true});const decoded=jpeg.decode(toByteArray(resized.base64!),{useTArray:true,formatAsRGBA:true});const chw=new Float32Array(3*SIZE*SIZE);for(let i=0;i<SIZE*SIZE;i++){chw[i]=(decoded.data[i*4]/255-.485)/.229;chw[SIZE*SIZE+i]=(decoded.data[i*4+1]/255-.456)/.224;chw[2*SIZE*SIZE+i]=(decoded.data[i*4+2]/255-.406)/.225}return{tensor:new ort.Tensor('float32',chw,[1,3,SIZE,SIZE]),rgba:decoded.data}}
async function exists(path:string){return (await FileSystem.getInfoAsync(path)).exists}
export async function modelStatus(){return{background:await exists(SEG),tags:await exists(TAG)}}
export async function removeBackground(uri:string,userId:number){if(!(await exists(SEG)))return uri;segmenter??=await ort.InferenceSession.create(SEG,{executionProviders:['cpu']});const{tensor,rgba}=await tensorFromImage(uri);const out=await segmenter.run({[segmenter.inputNames[0]]:tensor});const mask=out[segmenter.outputNames[0]].data as Float32Array;for(let i=0;i<SIZE*SIZE;i++)rgba[i*4+3]=Math.max(0,Math.min(255,Math.round(Number(mask[i])*255)));const png=encode({width:SIZE,height:SIZE,data:rgba,channels:4});const target=await processedPath(userId);await FileSystem.writeAsStringAsync(target,fromByteArray(png),{encoding:FileSystem.EncodingType.Base64});return target}
export async function analyzeGarment(uri:string):Promise<DraftAnalysis>{const fallback:DraftAnalysis={name:'Nueva prenda',category:'top',subcategory:'',color:'',material:'',style:'',season:'',brand:'',confidence:0};if(!(await exists(TAG)))return fallback;classifier??=await ort.InferenceSession.create(TAG,{executionProviders:['cpu']});const{tensor}=await tensorFromImage(uri);const out=await classifier.run({[classifier.inputNames[0]]:tensor});const pick=(key:string,n:string[])=>softPick((out[key]?.data||[]) as ArrayLike<number>,n);return{name:'Nueva prenda',category:pick('category',labels.category) as Slot,subcategory:'',color:pick('color',labels.color),material:pick('material',labels.material),style:pick('style',labels.style),season:pick('season',labels.season),brand:'',confidence:Number(out.confidence?.data?.[0]||0)}}
export async function installModelFromUri(kind:'background'|'tags',source:string){await FileSystem.makeDirectoryAsync(MODELS,{intermediates:true});await FileSystem.copyAsync({from:source,to:kind==='background'?SEG:TAG})}
