import{useState}from'react';
import{Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import*as ImagePicker from'expo-image-picker';
import{database}from'../db/database';
import{analyzeGarment,removeBackground}from'../services/localAI';
import{persistOriginal}from'../services/storage';
import type{DraftAnalysis,Slot}from'../types';
import{C}from'../theme/tokens';

const categories:{id:Slot;label:string}[]=[{id:'top',label:'Arriba'},{id:'bottom',label:'Abajo'},{id:'shoes',label:'Calzado'},{id:'accessory',label:'Accesorio'}];

export function AddGarmentScreen({userId,close,saved}:{userId:number;close:()=>void;saved:()=>void}){
 const[uris,setUris]=useState<string[]>([]);
 const[draft,setDraft]=useState<DraftAnalysis|null>(null);
 const[processed,setProcessed]=useState<{original_uri:string;processed_uri:string}[]>([]);
 const[price,setPrice]=useState('');
 const[busy,setBusy]=useState(false);
 const addUris=(incoming:string[])=>setUris(current=>[...current,...incoming.filter(uri=>!current.includes(uri))].slice(0,8));
 const pick=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:Math.max(1,8-uris.length),quality:1});if(!r.canceled)addUris(r.assets.map(asset=>asset.uri))};
 const camera=async()=>{const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted){Alert.alert('Permiso de cámara','Permite la cámara si quieres fotografiar una prenda desde aquí.');return}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:1});if(!r.canceled)addUris([r.assets[0].uri])};
 const run=async()=>{if(!uris.length)return;setBusy(true);try{
  const originals:string[]=[];const cutouts:string[]=[];
  // Vision can use significant RAM; process one image at a time on an iPhone.
  for(const uri of uris){const original=await persistOriginal(uri,userId);originals.push(original);cutouts.push(await removeBackground(original,userId))}
  setProcessed(originals.map((original,index)=>({original_uri:original,processed_uri:cutouts[index]})));
  setDraft(await analyzeGarment(originals[0]));
 }catch(error){Alert.alert('Procesamiento local',error instanceof Error?error.message:'No se pudo preparar esta prenda.')}finally{setBusy(false)}};
 const update=(key:keyof DraftAnalysis,value:string)=>setDraft(current=>current?{...current,[key]:value}:current);
 const save=()=>{if(!draft||!processed.length)return;const parsed=Number(price.replace(',','.'));database.createGarment(userId,{name:draft.name.trim()||'Nueva prenda',category:categories.some(item=>item.id===draft.category)?draft.category:'top',subcategory:draft.subcategory.trim()||null,color:draft.color.trim()||null,material:draft.material.trim()||null,style:draft.style.trim()||null,season:draft.season.trim()||null,brand:draft.brand.trim()||null,price:Number.isFinite(parsed)&&parsed>=0?parsed:null},processed);saved();close()};
 return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.row}><Pressable onPress={close}><Text style={s.cancel}>Cancelar</Text></Pressable><Text style={s.title}>Nueva pieza</Text><View style={{width:60}}/></View>
 {!draft?<><View style={s.intro}><Text style={s.introTitle}>Frente, espalda y detalles.</Text><Text style={s.introCopy}>La IA de este iPhone recorta y propone etiquetas. Nada se envía fuera del dispositivo.</Text></View><Pressable style={s.drop} onPress={pick}><Text style={s.camera}>＋</Text><Text style={s.dropTitle}>Añadir fotografías</Text><Text style={s.muted}>Hasta 8 fotos de una misma prenda</Text></Pressable><View style={s.photoActions}><Pressable style={s.secondary} onPress={camera}><Text style={s.secondaryText}>Usar cámara</Text></Pressable><Pressable style={s.secondary} onPress={pick}><Text style={s.secondaryText}>Fototeca</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.thumbs}>{uris.map(uri=><View key={uri} style={s.thumbWrap}><Image source={{uri}} style={s.thumb}/><Pressable accessibilityLabel="Eliminar foto" onPress={()=>setUris(all=>all.filter(item=>item!==uri))} style={s.remove}><Text style={s.removeText}>×</Text></Pressable></View>)}</ScrollView><Pressable disabled={!uris.length||busy} style={[s.primary,(!uris.length||busy)&&s.disabled]} onPress={run}><Text style={s.primaryText}>{busy?'Procesando en este iPhone…':'Continuar con IA local'}</Text></Pressable></>:<><Text style={s.kicker}>REVISA Y EDITA LO QUE QUIERAS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.processedThumbs}>{processed.map(photo=><Image key={photo.processed_uri} source={{uri:photo.processed_uri}} style={s.processedThumb}/>)}</ScrollView><Text style={s.label}>CATEGORÍA</Text><View style={s.chips}>{categories.map(item=><Pressable key={item.id} onPress={()=>setDraft(current=>current?{...current,category:item.id}:current)} style={[s.chip,draft.category===item.id&&s.chipActive]}><Text style={[s.chipText,draft.category===item.id&&s.chipActiveText]}>{item.label}</Text></Pressable>)}</View>{(['name','subcategory','color','material','style','season','brand'] as const).map(key=><View key={key}><Text style={s.label}>{fieldName(key)}</Text><TextInput style={s.input} value={String(draft[key]||'')} onChangeText={value=>update(key,value)} placeholder={placeholder(key)} placeholderTextColor="#B1B1B6"/></View>)}<View><Text style={s.label}>PRECIO DE COMPRA · OPCIONAL</Text><TextInput style={s.input} value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="0,00 €" placeholderTextColor="#B1B1B6"/></View><View style={s.localNote}><Text style={s.localNoteTitle}>{draft.confidence>0?'Etiquetas sugeridas localmente':'Revisión manual'}</Text><Text style={s.localNoteCopy}>{draft.confidence>0?'Comprueba los datos antes de guardar: una foto no siempre permite saber material o marca con certeza.':'Tu dispositivo no tiene Vision disponible para esta foto; puedes completar todo manualmente.'}</Text></View><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>Guardar en mi armario</Text></Pressable></>}</ScrollView>
}

function fieldName(value:string){return({name:'NOMBRE',subcategory:'SUBCATEGORÍA',color:'COLOR',material:'MATERIAL',style:'ESTILO',season:'TEMPORADA',brand:'MARCA'}as Record<string,string>)[value]}
function placeholder(value:string){return({name:'Ej. Camiseta boxy',subcategory:'Ej. Camiseta, chaqueta o gorra',color:'Ej. Negro',material:'Ej. Algodón',style:'Ej. Streetwear',season:'Ej. Todo el año',brand:'Ej. Nike'}as Record<string,string>)[value]}

const s=StyleSheet.create({page:{flex:1,backgroundColor:C.paper},content:{padding:20,paddingTop:58,paddingBottom:50},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cancel:{fontWeight:'700',width:60},title:{fontSize:19,fontWeight:'900'},intro:{marginTop:28},introTitle:{fontSize:26,fontWeight:'900',letterSpacing:-.7},introCopy:{color:C.muted,lineHeight:20,marginTop:7},drop:{height:220,borderWidth:1,borderStyle:'dashed',borderColor:C.muted,alignItems:'center',justifyContent:'center',marginTop:24,backgroundColor:C.white},camera:{fontSize:45},dropTitle:{fontSize:18,fontWeight:'800'},muted:{color:C.muted,marginTop:6},photoActions:{flexDirection:'row',gap:10,marginTop:10},secondary:{flex:1,height:44,borderRadius:22,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',backgroundColor:C.white},secondaryText:{fontWeight:'800',fontSize:13},thumbs:{gap:9,paddingVertical:15},thumbWrap:{width:82,height:82},thumb:{width:82,height:82,borderRadius:10},remove:{position:'absolute',right:-4,top:-5,width:22,height:22,borderRadius:11,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'},removeText:{color:'#fff',fontSize:17,lineHeight:19},primary:{height:54,backgroundColor:C.ink,alignItems:'center',justifyContent:'center',marginTop:18,borderRadius:27},primaryText:{color:C.white,fontWeight:'900'},disabled:{opacity:.4},kicker:{fontSize:11,letterSpacing:2,fontWeight:'800',color:C.muted,marginTop:30},processedThumbs:{gap:10,marginVertical:16},processedThumb:{width:150,height:180,resizeMode:'contain',borderRadius:13,backgroundColor:C.panel},label:{fontSize:10,letterSpacing:1.5,fontWeight:'800',color:C.muted,marginTop:15},input:{height:48,borderBottomWidth:1,borderColor:C.line,fontSize:17},chips:{flexDirection:'row',gap:8,flexWrap:'wrap',marginTop:9},chip:{borderWidth:1,borderColor:C.line,borderRadius:19,paddingHorizontal:13,paddingVertical:9,backgroundColor:C.white},chipActive:{backgroundColor:C.ink,borderColor:C.ink},chipText:{fontSize:12,fontWeight:'800'},chipActiveText:{color:'#fff'},localNote:{backgroundColor:'#EEF6FF',padding:14,borderRadius:14,marginTop:21},localNoteTitle:{fontWeight:'900',fontSize:13},localNoteCopy:{color:'#466179',fontSize:12,lineHeight:18,marginTop:4}});
