import{useState}from'react';
import{Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import*as ImagePicker from'expo-image-picker';
import{database}from'../db/database';
import{extractOutfitPieces,type OutfitExtraction}from'../services/localAI';
import type{Slot}from'../types';

const categories:{id:Slot;label:string}[]=[{id:'accessory',label:'Accesorio'},{id:'top',label:'Arriba'},{id:'bottom',label:'Abajo'},{id:'shoes',label:'Zapatos'}];
type Candidate=OutfitExtraction&{selected:boolean};

export function OutfitImportScreen({userId,close,saved}:{userId:number;close:()=>void;saved:()=>void}){
 const[source,setSource]=useState<string|null>(null),[pieces,setPieces]=useState<Candidate[]>([]),[busy,setBusy]=useState(false);
 const choose=async()=>{const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:false,quality:1});if(!picked.canceled)setSource(picked.assets[0].uri)};
 const extract=async()=>{if(!source)return;setBusy(true);try{setPieces((await extractOutfitPieces(source,userId)).map(piece=>({...piece,selected:piece.id!=='accessory'})))}catch(error){Alert.alert('No se pudo leer el outfit',error instanceof Error?error.message:'Prueba con una foto vertical de cuerpo entero.')}finally{setBusy(false)}};
 const edit=(index:number,patch:Partial<Candidate['draft']>)=>setPieces(all=>all.map((piece,i)=>i===index?{...piece,draft:{...piece.draft,...patch}}:piece));
 const save=()=>{const picked=pieces.filter(piece=>piece.selected);if(!picked.length)return Alert.alert('Elige al menos una pieza','Toca las piezas que quieras guardar.');for(const piece of picked){database.createGarment(userId,{name:piece.draft.name.trim()||'Nueva prenda',category:piece.draft.category,subcategory:piece.draft.subcategory||null,color:piece.draft.color||null,material:piece.draft.material||null,style:piece.draft.style||null,season:piece.draft.season||null,brand:null,price:null},[{original_uri:piece.original_uri,processed_uri:piece.processed_uri}])}saved();close()};
 return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.head}><Pressable onPress={close}><Text style={s.cancel}>Cancelar</Text></Pressable><Text style={s.title}>Desde un outfit</Text><View style={{width:60}}/></View>
 {!pieces.length?<><Text style={s.hero}>Una foto. Varias piezas.</Text><Text style={s.copy}>Importa un fit vertical completo. Este iPhone conserva la parte visible de cada prenda, quita el fondo localmente y propone sus datos. No inventa lo que la foto no muestra.</Text><Pressable onPress={choose} style={s.photo}>{source?<Image source={{uri:source}} style={s.source}/>:<><Text style={s.plus}>＋</Text><Text style={s.photoText}>Elegir foto del outfit</Text></>}</Pressable><Text style={s.tip}>Mejor resultado: cuerpo entero, buena luz y fondo que contraste.</Text><Pressable disabled={!source||busy} onPress={extract} style={[s.primary,(!source||busy)&&s.disabled]}><Text style={s.primaryText}>{busy?'Extrayendo en este iPhone…':'Detectar prendas visibles'}</Text></Pressable></>:<><Text style={s.resultTitle}>Revisa las piezas visibles</Text><Text style={s.resultCopy}>Desactiva lo que no corresponda; puedes editar nombre y categoría antes de guardar.</Text>{pieces.map((piece,index)=><View key={piece.id} style={[s.card,!piece.selected&&s.cardOff]}><Pressable onPress={()=>setPieces(all=>all.map((item,i)=>i===index?{...item,selected:!item.selected}:item))} style={[s.tick,piece.selected&&s.tickOn]}><Text style={s.tickText}>{piece.selected?'✓':''}</Text></Pressable><Image source={{uri:piece.processed_uri}} style={s.image}/><View style={s.form}><TextInput value={piece.draft.name} onChangeText={name=>edit(index,{name})} style={s.name} placeholder="Nombre"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map(category=><Pressable key={category.id} onPress={()=>edit(index,{category:category.id})} style={[s.chip,piece.draft.category===category.id&&s.chipOn]}><Text style={[s.chipText,piece.draft.category===category.id&&s.chipTextOn]}>{category.label}</Text></Pressable>)}</ScrollView><TextInput value={piece.draft.color} onChangeText={color=>edit(index,{color})} style={s.detail} placeholder="Color (opcional)" placeholderTextColor="#A0A0A6"/></View></View>)}<Pressable onPress={save} style={s.primary}><Text style={s.primaryText}>Guardar piezas seleccionadas</Text></Pressable><Pressable onPress={()=>{setPieces([]);setSource(null)}} style={s.tryAgain}><Text style={s.tryText}>Probar otra foto</Text></Pressable></>}</ScrollView>
}

const s=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},content:{padding:20,paddingTop:58,paddingBottom:40},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cancel:{fontWeight:'800',width:60},title:{fontWeight:'900',fontSize:18},hero:{fontSize:29,fontWeight:'900',letterSpacing:-.8,marginTop:34},copy:{color:'#74747B',lineHeight:21,marginTop:9},photo:{height:285,marginTop:23,borderRadius:22,backgroundColor:'#F4F4F6',alignItems:'center',justifyContent:'center',overflow:'hidden',borderWidth:1,borderColor:'#E7E7EA'},source:{width:'100%',height:'100%',resizeMode:'cover'},plus:{fontSize:43},photoText:{fontWeight:'900',marginTop:7},tip:{fontSize:12,lineHeight:18,color:'#85858B',marginTop:11},primary:{height:54,borderRadius:27,backgroundColor:'#050505',alignItems:'center',justifyContent:'center',marginTop:22},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.4},resultTitle:{fontSize:24,fontWeight:'900',marginTop:27},resultCopy:{fontSize:13,color:'#777',lineHeight:19,marginTop:5},card:{minHeight:145,marginTop:16,borderRadius:18,borderWidth:1,borderColor:'#E5E5E8',backgroundColor:'#fff',padding:11,flexDirection:'row'},cardOff:{opacity:.45},tick:{position:'absolute',right:10,top:10,zIndex:3,width:25,height:25,borderRadius:13,borderWidth:1,borderColor:'#D2D2D6',backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},tickOn:{backgroundColor:'#050505',borderColor:'#050505'},tickText:{color:'#fff',fontWeight:'900'},image:{width:112,height:122,resizeMode:'contain',backgroundColor:'#F8F8F8',borderRadius:12},form:{flex:1,marginLeft:12,paddingTop:3},name:{fontSize:16,fontWeight:'900',height:34,padding:0,paddingRight:20},chips:{gap:6,paddingVertical:8},chip:{borderWidth:1,borderColor:'#E0E0E4',borderRadius:14,paddingHorizontal:8,paddingVertical:5},chipOn:{backgroundColor:'#050505',borderColor:'#050505'},chipText:{fontSize:10,fontWeight:'800'},chipTextOn:{color:'#fff'},detail:{height:31,borderBottomWidth:1,borderColor:'#E7E7E9',fontSize:12,padding:0},tryAgain:{height:44,alignItems:'center',justifyContent:'center'},tryText:{fontWeight:'800',color:'#555'} });
